### ISSUE TITLE
Access denied When putting the class file into a new jar file

### ISSUE THREAD

**Issue by Dumpzy** [DxxxxY/Hephaestus#11]
Access denied When putting the class file into a new jar file (Not sure why need some help) thanks

**Comment by DxxxxY** [comment]
Your filesystem is restricting Java from accessing that file. Either the path is incorrect (the file doesn't exist), or something is placing a lock on that file. I think you should make sure that it is the ABSOLUTE PATH to the new jar. (example: C:\examplefolder\example.jar)
