### ISSUE TITLE
is piece of garbage

### ISSUE THREAD

**Issue by custom1337** [DxxxxY/Hephaestus#12]
you are kind of a monkey you know is no good

**Comment by DxxxxY** [comment]
Hahahahaha.

Are you still that mad that both my R.A.T and Builder are better than yours? Idk why you even released it. Also sorry to hear about your Github account 😞

**Comment by custom1337** [comment]
nah bro ik your rat is good :D i was just really bored since i woke up now

**Comment by custom1337** [comment]
and also damn you replied fast

**Comment by DxxxxY** [comment]
Damn, what happened bro? What made you change like that?

**Comment by TheDingOfTheHud** [comment]
bro was scared

**Comment by MouseHubMC** [comment]
> Hahahahaha.
> 
> Are you still that mad that both my R.A.T and Builder are better than yours? Idk why you even released it. Also sorry to hear about your Github account 😞

it's a impersonator

**Comment by DxxxxY** [comment]
Damn, I thought he was the real one.
