### ISSUE TITLE
[INVALID] Wrong path for jar command.

### ISSUE THREAD

**Issue by ShinyKira** [DxxxxY/Hephaestus#7]
java -jar Hephaestus-2.0-RELEASE.jar
Error: Unable to access jarfile Hephaestus-2.0-RELEASE.jar

. Tried it many times, also tried to update java, restart pc, etc. doesnt work.

need fixes.

**Comment by DxxxxY** [comment]
You're trying to open a file which isn't at the path your command is at. You'll need the full path to the .jar or you'll need to cd into the directory. That's how a file system works. This isn't an error.
